apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: happy-borg
spec:
  selector:
    matchLabels:
      name: happy-borg
  template:
    metadata:
      labels:
        name: happy-borg
    spec:
#      initContainers:
#        - name: init-header
#          image: ubuntu
#          volumeMounts:
#            - name: sys # mount the debug filesystem
#              mountPath: /sys
#              readOnly: true
#            - name: headers # mount the kernel headers required by bcc
#              mountPath: /usr/src
#              readOnly: false
#            - name: modules # mount the kernel modules required by bcc
#              mountPath: /lib/modules
#              readOnly: true
#          command:
#            - sh
#            - "-c"
#            - |-
#              apt update
#              apt install -y linux-headers-$(uname -r)
      containers:
        - name: execsnoop
          image: gcr.io/hanliu-20211231-155028/ebpf-kprobe:test3
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - name: sys # mount the debug filesystem
              mountPath: /sys
              readOnly: true
            - name: headers # mount the kernel headers required by bcc
              mountPath: /usr/src
              readOnly: true
            - name: modules # mount the kernel modules required by bcc
              mountPath: /lib/modules
              readOnly: true
            - name: localtime # mount the kernel modules required by bcc
              mountPath: /etc/localtime
              readOnly: true
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: headers
          hostPath:
            path: /usr/src
        - name: modules
          hostPath:
            path: /lib/modules
        - name: proc
          hostPath:
            path: /proc
        - name: localtime
          hostPath:
            path: /etc/localtime

