apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: happy-borg
spec:
  selector:
    matchLabels:
      name: happy-borg
  template:
    metadata:
      labels:
        name: happy-borg
    spec:
#      initContainers:
#        - name: init-header
#          image: ubuntu
#          volumeMounts:
#            - name: sys # mount the debug filesystem
#              mountPath: /sys
#              readOnly: true
#            - name: headers # mount the kernel headers required by bcc
#              mountPath: /usr/src
#              readOnly: false
#            - name: modules # mount the kernel modules required by bcc
#              mountPath: /lib/modules
#              readOnly: true
#          command:
#            - sh
#            - "-c"
#            - |-
#              apt update
#              apt install -y linux-headers-$(uname -r)
      containers:
        - name: ebpf-kprobe
          image: gcr.io/hanliu-20211231-155028/ebpf-kprobe:test3
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - name: sys # mount the debug filesystem
              mountPath: /sys
              readOnly: true
            - name: host
              mountPath: /host
              readOnly: true
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: host
          hostPath:
            path: /
            type: Directory