// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// Sends a greeting
	SingleCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error)
	StreamCall(ctx context.Context, opts ...grpc.CallOption) (Service_StreamCallClient, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) SingleCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error) {
	out := new(CallReply)
	err := c.cc.Invoke(ctx, "/Service/SingleCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StreamCall(ctx context.Context, opts ...grpc.CallOption) (Service_StreamCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/Service/StreamCall", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceStreamCallClient{stream}
	return x, nil
}

type Service_StreamCallClient interface {
	Send(*StreamRequest) error
	CloseAndRecv() (*StreamReply, error)
	grpc.ClientStream
}

type serviceStreamCallClient struct {
	grpc.ClientStream
}

func (x *serviceStreamCallClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceStreamCallClient) CloseAndRecv() (*StreamReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// Sends a greeting
	SingleCall(context.Context, *CallRequest) (*CallReply, error)
	StreamCall(Service_StreamCallServer) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) SingleCall(context.Context, *CallRequest) (*CallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleCall not implemented")
}
func (UnimplementedServiceServer) StreamCall(Service_StreamCallServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCall not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_SingleCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SingleCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Service/SingleCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SingleCall(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StreamCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceServer).StreamCall(&serviceStreamCallServer{stream})
}

type Service_StreamCallServer interface {
	SendAndClose(*StreamReply) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type serviceStreamCallServer struct {
	grpc.ServerStream
}

func (x *serviceStreamCallServer) SendAndClose(m *StreamReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceStreamCallServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleCall",
			Handler:    _Service_SingleCall_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCall",
			Handler:       _Service_StreamCall_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
